#!/bin/sh
SELF="$0"
if [ -L "$SELF" ]; then
  SELF="$(readlink -f "$SELF")"
fi
SCRIPT_DIR="$(cd "$(dirname "$SELF")" && pwd)"
exec erl -pa "$SCRIPT_DIR"/*/ebin -eval "kirari@@main:run(kirari)" -noshell -extra "$@"
